<html>
     <head>
          <title>Registration</title>
     </head>
     <body>
     <form action='' method="POST">
          <?php echo $this->registerForm->getElement('name'); ?>
          <?php echo $this->registerForm->getElement('email');?>
          <?php echo $this->registerForm->getElement('password');?>
          <?php //echo $this->employeeForm->getElement('number'); ?>
          <?php //echo $this->employeeForm->getElement('designation'); ?>
          <?php echo $this->registerForm->getElement('submit'); ?>
     </form>
     </body>
</html>